config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :trains do
      resources :carriages, shallow: true # частичная вложенность только для index create new
    end
    resources :routes
    resources :tickets
  end

  resources :tickets, only: [:create, :show]
  resources :searches, path: "search", only: [:new, :show, :edit]
  get '/search(.:format)' => 'searches#show'


  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :station_count

  before_validation :set_name

  private

  def set_name
    self.name = self.name.empty? ? "#{railway_stations.first.title} - #{railway_stations.last.title}" : self.name
  end

  def station_count
    errors.add(:base, "Route should contain more than 2 stations") if railway_stations.size < 2
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_with(model: @route) do |form| %>

  <%= render 'common/errors', resource: @route   %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :current_station , "Current Station"%>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title,{}, {:multiple => true} %>
  </div>

  <div class="actions">
    <%= form.submit "#{@route.new_record? ? 'Создать' : 'Изменить' }"%>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/admin/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes Note</h1>

<table>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/admin/routes/new.html.erb
<h1>New Roten</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/admin/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>
<!--<p>-->
<!--  <strong> On the Station -  </strong>-->
  <%#= @route.current_station.present? ? @route.current_station.title : "No route"  %>
<!--</p>-->
<p>
  <table>
    <thead>
    <tr>
      <td width="100px">Name</td>
      <td>Position</td>
    </tr>
    </thead>
    <tbody>
    <% @route.railway_stations.ordered.each do |rs| %>
      <tr>
        <td><%= rs.title %></td>
        <td>
          <%= form_tag update_position_railway_station_path(rs), method: :patch do %>
            <%= number_field_tag :position, rs.position_in(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag "Change!"%>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>