config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :railway_stations do
      patch :update_position, on: :member
    end
    resources :trains do
      resources :carriages, shallow: true # частичная вложенность только для index create new
    end
    resources :routes
    resources :tickets
  end

  resources :tickets, only: [:create, :show]
  resources :searches, path: "search", only: [:new, :show, :edit]
  get '/search(.:format)' => 'searches#show'


  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :carriages
  validates :number, presence: true

  belongs_to :current_station, class_name: "RailwayStation", foreign_key: :current_station_id
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id)
  end
end

app/views/admin/trains/_form.html.erb
<%= form_with(model: @train) do |form| %>

  <%= render 'common/errors', resource: @train   %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station , "Current Station"%>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="actions">
    <%= form.submit "#{@train.new_record? ? 'Создать' : 'Изменить' }"%>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/admin/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains Note</h1>

<table>
  <thead>
    <tr>
      <% if @trains.any? %> <th>Number</th> <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
                       <!--  <%= render @trains %>   -->
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form' %>


<%= link_to 'Back', trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <strong> On the Station -  </strong>
  <%= @train.current_station.present? ? @train.current_station.title : "No station"  %>
</p>

<p>
  <strong>Carriages</strong>
  <ul>
    <% @train.carriages.each do |car| %>
      <li><%= link_to "Carriage №#{car.number}", car %></li>
    <% end %>
  </ul>
</p>

<p>
  <%= link_to "Add Carriage", new_train_carriage_path(@train) %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>